### ISSUE TITLE
java.lang.Throwable: Recursion prevented when computing FileIndex extension

### ISSUE THREAD

**Issue by aroige** [cake-build/cake-rider#169] opened 2021-07-14 13:34 UTC
Plugin version: `1.0.0`
IDE version: `2021.1.3 (RD-211.7442.29)`
Operating system: `Windows 10`
Additional information:
```text
Had a solution opened,
File -> Open -> Another solution
Open in this window
```
Exception: `java.lang.Throwable: Recursion prevented when computing FileIndex extension`

Stacktrace:
java.lang.Throwable: Recursion prevented when computing FileIndex extension
	at com.intellij.javascript.nodejs.library.NodeModulesDirectoryManager.computeFileIndexExtensionPreventingRecursion(NodeModulesDirectoryManager.java:203)
	at com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider.getAdditionalProjectLibraries(NodeModulesSyntheticLibraryProvider.java:18)
	at com.intellij.openapi.roots.impl.RootIndex.buildRootInfo(RootIndex.java:243)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:72)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:56)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:171)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:154)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:181)
	at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:98)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getInfoForFileOrDirectory(ProjectFileIndexImpl.java:27)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isInContent(ProjectFileIndexImpl.java:196)
	at com.intellij.openapi.project.ProjectLocatorImpl.isUnder(ProjectLocatorImpl.java:61)
	at com.intellij.openapi.project.ProjectLocatorImpl.lambda$getProjectsForFile$1(ProjectLocatorImpl.java:75)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:844)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:51)
	at com.intellij.openapi.project.ProjectLocatorImpl.getProjectsForFile(ProjectLocatorImpl.java:73)
	at net.cakebuild.language.CakeFileType.isMyFileType(CakeFileType.kt:23)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getByFile(FileTypeManagerImpl.java:648)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:606)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:595)
	at com.intellij.openapi.vfs.VirtualFile.getFileType(VirtualFile.java:354)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getFileType(VirtualFileSystemEntry.java:578)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.computeCharset(VirtualFileSystemEntry.java:457)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getCharset(VirtualFileSystemEntry.java:445)
	at com.intellij.openapi.vfs.VfsUtilCore.loadText(VfsUtilCore.java:376)
	at com.intellij.openapi.vfs.VfsUtilCore.loadText(VfsUtilCore.java:372)
	at com.intellij.javascript.nodejs.PackageJsonData.loadText(PackageJsonData.java:436)
	at com.intellij.javascript.nodejs.PackageJsonData.doParse(PackageJsonData.java:418)
	at com.intellij.javascript.nodejs.PackageJsonData.lambda$getOrCreate$16(PackageJsonData.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:844)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.javascript.nodejs.PackageJsonData.getOrCreate(PackageJsonData.java:392)
	at com.intellij.javascript.nodejs.library.NodeModulesLibraryDirectory$PackageJsonFiles.lambda$new$0(NodeModulesLibraryDirectory.java:505)
	at com.intellij.openapi.project.ProjectLocator.computeWithPreferredProject(ProjectLocator.java:61)
	at com.intellij.javascript.nodejs.library.NodeModulesLibraryDirectory$PackageJsonFiles.lambda$new$1(NodeModulesLibraryDirectory.java:504)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1894)
	at com.intellij.javascript.nodejs.library.NodeModulesLibraryDirectory$PackageJsonFiles.<init>(NodeModulesLibraryDirectory.java:503)
	at com.intellij.javascript.nodejs.library.NodeModulesLibraryDirectory.doCreateLibrary(NodeModulesLibraryDirectory.java:117)
	at com.intellij.javascript.nodejs.library.NodeModulesLibraryDirectory.createLibrary(NodeModulesLibraryDirectory.java:105)
	at com.intellij.javascript.nodejs.library.NodeModulesLibraryDirectory.getLibrary(NodeModulesLibraryDirectory.java:93)
	at com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider.lambda$computeRoots$2(NodeModulesSyntheticLibraryProvider.java:29)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1977)
	at com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider.computeRoots(NodeModulesSyntheticLibraryProvider.java:25)
	at com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider.lambda$getAdditionalProjectLibraries$0(NodeModulesSyntheticLibraryProvider.java:18)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.javascript.nodejs.library.NodeModulesDirectoryManager.computeFileIndexExtensionPreventingRecursion(NodeModulesDirectoryManager.java:197)
	at com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider.getAdditionalProjectLibraries(NodeModulesSyntheticLibraryProvider.java:18)
	at com.intellij.openapi.roots.impl.RootIndex.buildRootInfo(RootIndex.java:243)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:72)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:56)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:171)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:154)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:181)
	at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:98)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getInfoForFileOrDirectory(ProjectFileIndexImpl.java:27)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isInContent(ProjectFileIndexImpl.java:196)
	at com.intellij.openapi.project.ProjectLocatorImpl.isUnder(ProjectLocatorImpl.java:61)
	at com.intellij.openapi.project.ProjectLocatorImpl.lambda$getProjectsForFile$1(ProjectLocatorImpl.java:75)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:844)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:51)
	at com.intellij.openapi.project.ProjectLocatorImpl.getProjectsForFile(ProjectLocatorImpl.java:73)
	at net.cakebuild.language.CakeFileType.isMyFileType(CakeFileType.kt:23)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getByFile(FileTypeManagerImpl.java:648)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:606)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:595)
	at com.intellij.openapi.vfs.VirtualFile.getFileType(VirtualFile.java:354)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getFileType(VirtualFileSystemEntry.java:578)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.isBinaryWithoutDecompiler(FileDocumentManagerBase.java:134)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:41)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.lambda$processFiles$1(EditorsSplitters.java:971)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:970)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:933)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$ConfigTreeReader.process(EditorsSplitters.java:925)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.restoreEditors(EditorsSplitters.java:266)
	at com.intellij.openapi.fileEditor.impl.OpenFilesActivity.runActivity(OpenFilesActivity.java:36)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:335)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:309)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$executeActivitiesFromExtensionPoint$2(StartupManagerImpl.java:207)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processImplementations(ExtensionPointImpl.java:320)
	at com.intellij.ide.startup.impl.StartupManagerImpl.executeActivitiesFromExtensionPoint(StartupManagerImpl.java:188)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartUpActivities(StartupManagerImpl.java:180)
	at com.intellij.ide.startup.impl.StartupManagerImpl.projectOpened(StartupManagerImpl.java:145)
	at com.intellij.openapi.project.impl.ProjectManagerExImplKt.openProject(ProjectManagerExImpl.kt:395)
	at com.intellij.openapi.project.impl.ProjectManagerExImplKt.access$openProject(ProjectManagerExImpl.kt:1)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$openProjectAsync$1.invoke(ProjectManagerExImpl.kt:124)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$openProjectAsync$1.invoke(ProjectManagerExImpl.kt:55)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:93)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:70)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by nils-a** [comment] 2021-07-14 19:01
@aroige thank you for the report.
Was any of the project JavaScript or Node related? I see a lot of lines containing js/node stuff like e.g. `com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider`...

**Comment by aroige** [comment] 2021-07-14 23:03
Hi!
Yes the solution that was open before i switched to another one had at
least two projects using node.js

Den ons 14 juli 2021 21:01Nils Andresen ***@***.***> skrev:

**Comment by nils-a** [comment] 2021-07-15 06:33
Thanks for confirming. I am able to reproduce it, now.
I'll close this issue as a duplicate of #160

**Closed by nils-a** 2021-07-15 06:33 UTC
