### ISSUE TITLE
com.intellij.diagnostic.PluginException: Cannot init toolwindow net.cakebuild.toolwindow.CakeTasksWindowFactory@61fdfbda [Plugin: net.cakebuild.cakerider]

### ISSUE THREAD

**Issue by travistodd099** [cake-build/cake-rider#269] opened 2022-08-12 22:06 UTC
Plugin version: `3.2.0`
IDE version: `2022.2.1 (RD-222.3739.37)`
Operating system: `Windows 10`
Exception: `com.intellij.diagnostic.PluginException: Cannot init toolwindow net.cakebuild.toolwindow.CakeTasksWindowFactory@61fdfbda [Plugin: net.cakebuild.cakerider]`
Stacktrace:
```text


StackTrace too long. Please copy the StackTrace here manually.


```

**Comment by nils-a** [comment] 2022-08-13 19:58
This happens since Rider version 2022.1, when multiple plugins are installed that provide a ToolWindow named Cake Tasks.

Specifically, this error occurs, if the [CakeIntegration-Plugin](https://plugins.jetbrains.com/plugin/13237-cakeintegration) is installed alongside of Cake for Rider.

Can you confirm that you have both plugins installed?

**Comment by nils-a** [comment] 2022-08-23 11:52
Closing this as a duplicate of #239. Feel free to comment if it should be re-opened.

**Closed by nils-a** 2022-08-23 11:52 UTC
