### ISSUE TITLE
java.lang.Throwable: Recursion prevented when computing FileIndex extension

### ISSUE THREAD

**Issue by tgriley** [cake-build/cake-rider#173] opened 2021-07-16 09:04 UTC
Plugin version: `1.0.0`
IDE version: `2021.1.4 (RD-211.7628.50)`
Operating system: `Windows 10`
Exception: `java.lang.Throwable: Recursion prevented when computing FileIndex extension`
Stacktrace:
```text


StackTrace too long. Please copy the StackTrace here manually.


```

**Comment by nils-a** [comment] 2021-07-16 09:16
@tgriley Thank you for the report. 
That bug will be solved in the upcoming version.
Closing this as a duplicate of #160

**Closed by nils-a** 2021-07-16 09:16 UTC
