### ISSUE TITLE
Rider 2024.1 with Cake for Rider plugin breaks code analysis and syntax highlighting

### ISSUE THREAD

**Issue by Sebazzz** [cake-build/cake-rider#420] opened 2024-04-10 08:47 UTC
Though #400 adds support for Rider 2024.1-EAP, it appears that in the stable release of Rider, there is an issue with Cake for Rider that causes code analysis to silently fail, which then prevents Rider from doing proper syntax highlighting in any C# (+ other languages?) files.

Please see:

- https://youtrack.jetbrains.com/issue/RIDER-110680/The-code-is-not-colored
- https://youtrack.jetbrains.com/issue/RIDER-110670/Code-Analysis-silently-fails-in-all-projects-after-upgrading-to-Rider-2024.1

**Comment by elarrieux** [comment] 2024-04-10 15:44
I was having the same issue, disabling the plugin fixed it for me.

**Comment by mwmatlock-eprod** [comment] 2024-04-17 16:35
Same issue, uninstalling the plugin and rebooting my computer fixed it for me.

**Comment by nils-a** [comment] 2024-05-03 21:48
I have uploaded the version produced by #426 to https://plugins.jetbrains.com/plugin/15729-cake-for-rider/versions/beta/531923. In my tests, that PR also seemed to resolve this issue.

Does anyone of you (@Sebazzz, @elarrieux, @mwmatlock-eprod) have the cycles to download that version and test it manually?

**Comment by nils-a** [comment] 2024-05-14 18:15
I've gotten one feedback (in [YouTrack RIDER-111252](https://youtrack.jetbrains.com/issue/RIDER-111252/Rider-ignore-color-scheme-in-new-version-and-become-gray)) that the newest [release 8.0.2](https://github.com/cake-build/cake-rider/releases/tag/8.0.2) fixes this problem.

Hence, I'm going to label this bug as a duplicate of #422 (which is the one that was fixed in release 8.0.2) and close it.

**Closed by nils-a** 2024-05-14 18:15 UTC
Labels: Bug
