### ISSUE TITLE
com.intellij.diagnostic.PluginException: Cannot init toolwindow net.cakebuild.toolwindow.CakeTasksWindowFactory@3dd1d8b2 [Plugin: net.cakebuild.cakerider]

### ISSUE THREAD

**Issue by bbat42** [cake-build/cake-rider#278] opened 2022-09-14 09:38 UTC
Plugin version: `3.2.0`
IDE version: `2022.1 (RD-221.5080.236)`
Operating system: `Windows 10`
Exception: `com.intellij.diagnostic.PluginException: Cannot init toolwindow net.cakebuild.toolwindow.CakeTasksWindowFactory@3dd1d8b2 [Plugin: net.cakebuild.cakerider]`
Stacktrace:
```text


StackTrace too long. Please copy the StackTrace here manually.


```

**Comment by nils-a** [comment] 2022-09-14 18:50
This happens since Rider version 2022.1, when multiple plugins are installed that provide a ToolWindow with the same name.

Specifically, this error occurs, if the [CakeIntegration-Plugin](https://plugins.jetbrains.com/plugin/13237-cakeintegration) is installed alongside of Cake for Rider, as both implement a ToolWindow named 'Cake Tasks'.

Closing this as a duplicate of https://github.com/cake-build/cake-rider/issues/239.

**Closed by nils-a** 2022-09-14 18:50 UTC
