### ISSUE TITLE
com.intellij.diagnostic.PluginException: Cannot init toolwindow net.cakebuild.toolwindow.CakeTasksWindowFactory@23ad3f1 [Plugin: net.cakebuild.cakerider]

### ISSUE THREAD

**Issue by oneincgithub** [cake-build/cake-rider#241] opened 2022-05-02 17:30 UTC
Plugin version: `3.1.0`
IDE version: `2022.1.1 (RD-221.5591.20)`
Operating system: `Windows 10`
Exception: `com.intellij.diagnostic.PluginException: Cannot init toolwindow net.cakebuild.toolwindow.CakeTasksWindowFactory@23ad3f1 [Plugin: net.cakebuild.cakerider]`
Stacktrace:
```text


StackTrace too long. Please copy the StackTrace here manually.


```

**Comment by nils-a** [comment] 2022-05-05 19:26
Closing this as a duplicate of #240 and/or #239

**Closed by nils-a** 2022-05-05 19:26 UTC
